### ISSUE TITLE
Cannot import split module

### ISSUE THREAD

**Issue by Rajratnpranesh** [frankkramer-lab/covid19.MIScnn#10]
Hey guys,
Great work. I am trying to reproduce the results from your paper.
Here is the error I am getting 
```

2020-07-22 15:59:09.423261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "scripts/run_preprocessing.py", line 25, in <module>
    from miscnn.evaluation.cross_validation import split_folds
ImportError: cannot import name 'split_folds
```

Please have a look and suggest any fix

Thanks

**Comment by muellerdo** [comment]
Hey @Rajratnpranesh,

you are right. The required MIScnn version in the requirements.txt is 0.33 but it should be 0.34.
I updated the requirements.txt.

I will try to fully reproduce it, as well, in a new docker container at the end of this week in order to ensure full reproducibility.

Thanks you for pointing this out!

Cheers,
Dominik

**Comment by Rajratnpranesh** [comment]
Hey Muellerdo,

Thank you so much for your kind help. 
That's great I will try to reproduce the results.

Have a great day!!!!

Cheers 
Raj
