### ISSUE TITLE
About running errors

### ISSUE THREAD

**Issue by 10TREE-YEAR** [frankkramer-lab/covid19.MIScnn#13]
Hello, I'm sorry to disturb you, but I encountered some problems while running the program you wrote. I hope you can answer.
In the process of running run_miscnn.py, it always shows that there is no imaging.nii.gz file. I have copied it from other sources. If it exists, it still reports this error. So I want to ask, did you pass other files? We have processed the data and look forward to your reply. Greatful.

**Comment by muellerdo** [comment]
Hey @10TREE-YEAR,

thanks for your interest in this study.

Can you elaborate a little bit more on: 
> I have copied it from other sources.

Exceptions with missing 'imaging.nii.gz' indicating that the dataset file structure is either incorrect or the dataset was not correctly downloaded.

> So I want to ask, did you pass other files?

There was no additional files used for this study. In order to fully reproduce this study, it is only required to run the 'scripts/download_data.py' script. It will automatically download the dataset from Ma Jun et al. and parse it into the correct file structure for MIScnn.

> If it exists, it still reports this error.
> ...
> We have processed the data

What exactly do you mean with "processed"?
If you are seeing that the dataset is prepared into the correct file structure, I would take a wild guess that it has something todo with user rights e.g. that the process has no reading rights on the imaging files, maybe.

Hope that I was able to help.

Cheers,
Dominik

**Comment by 10TREE-YEAR** [comment]
Thank you for your reply. After reading your reply, I think it may be that I have changed the data set and the previous processing is not appropriate, so the code cannot be operated during the data processing. After I re-downloaded the data set and re-imported predictions.zip, it was able to proceed successfully.
