### ISSUE TITLE
Patchwise Overlap 

### ISSUE THREAD

**Issue by muzaffersenkal** [frankkramer-lab/covid19.MIScnn#18]
Hi,

I've noticed something that Patchwise Overlap  is  80x80x40 in the paper but it is 80x80x30 in the code. If overlap shape is not half of patch shape , is that okey ?

**Comment by muellerdo** [comment]
Hey @muzaffersenkal,

sorry for the late reply.

The patchwise overlap can be freely selected, so it don't have to be half of your patch shape.

The problem on the dataset we used was that one sample has a smaller z-axis than 40 (something about 38 if I remember correctly). This case lead to an error in the old MIScnn version at that time which is why we used 80x80x30 at first.
After we fixed this bug in MIScnn, we rerun the analysis from our paper with 80x80x40 but it didn't change anything performance-wise.

The main point is that the overlap is big enough to cover all edges, due to the prediction on patch edges are more unreliable. In my experiments I find a good rule of thumb that the overlap is at least 10-20 pixel on each axis.

Cheers,
Dominik
