### ISSUE TITLE
load_csv2fold

### ISSUE THREAD

**Issue by kirmans** [frankkramer-lab/covid19.MIScnn#21]
Hi @muellerdo 

I am using your [MIScnn](https://github.com/frankkramer-lab/MIScnn)  framework from installing directly from Github.  I am not using (pip installation). But in [cross validation file](https://github.com/frankkramer-lab/MIScnn/blob/master/miscnn/evaluation/cross_validation.py) I can't file "load_csv2fold". So in [run_miscnn.py](https://github.com/frankkramer-lab/covid19.MIScnn/blob/master/scripts/run_miscnn.py) line: 32 give error.

**Comment by muellerdo** [comment]
Hey @kirmans,

because the newest version of MIScnn uses JSON as format for storing fold information instead of CSV.
This repo is frozen to MIScnn version `miscnn==0.34` as stated in the requirements.txt.

You can either downgrade or replace the two lines of code with the newer `load_disk2fold()` function.

Cheers,
Dominik
