### ISSUE TITLE
Error while executing download data script

### ISSUE THREAD

**Issue by saahiluppal** [frankkramer-lab/covid19.MIScnn#25]
Executing ```scripts/download_data.py``` gives following error
```bash
$ python3 scripts/download_data.py

INFO: Downloading Volumes
COVID-19-CT-Seg_20cases.zip?download=1:   0%|                   | 1.20k/1.11G [00:00<225:54:25, 1.36kB/s]
INFO: Downloading Segmentations
Lung_and_Infection_Mask.zip?download=1:   0%|                     | 1.20k/11.7M [00:00<2:24:22, 1.35kB/s]
INFO: Obtain sample list from the volumes ZIP file
Traceback (most recent call last):
  File "scripts/download_data.py", line 85, in <module>
    with zipfile.ZipFile(path_vol_zip, "r") as zip_vol:
  File "/home/cinnamon/Repositories/miniconda3/envs/covid/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/home/cinnamon/Repositories/miniconda3/envs/covid/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

How to overcome this issue

**Comment by muellerdo** [comment]
Hey @saahiluppal,

can you verify that the dataset was correctly downloaded?
I would take a guess that there was some downloading issue resulting in corrupted files.

The download links as well as the script still works on my end.

Cheers,
Dominik

**Comment by muellerdo** [comment]
Please also verify if the python script has enough permissions to create and delete files/directories in the current working directory.

**Comment by saahiluppal** [comment]
[Here](https://gist.github.com/saahiluppal/05de135bd0c503a1e04e700fbe893ceb) is the gist from my colab run.
As you can see, the data doesn't even start to download and i guess that's why zip says it is not a valid file.

**Comment by muellerdo** [comment]
Mhm, interesting.

If you open up the downloaded file with a random text editor or via cat/vim/nano, it shows the Zenodo reponse.  
-> Google Colab is IP blocked from automatic downloading from Zenodo.

Zenodo probably wants Google Colab users to use their API to download files in large quantity instead of just downloading it with the frontend link (as I did).
https://developers.zenodo.org/#rest-api

You can either download the dataset locally on your computer (<2GB) and then upload it to your Gdrive, 
or you can adjust the script by using your personal token for downloading from Zenodo.

Here is the Zenodo repository of our used dataset: https://zenodo.org/record/3757476#.YMDcJkxCSHs

Hope that I was able to help.

Cheers,
Dominik

**Comment by saahiluppal** [comment]
Got it, Downloading dataset locally.

Thank you for this awesome project and thank you for your help
